# Generated by Django 4.0.2 on 2022-02-17 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_remove_usertext_times_followed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTextAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlapp.usertext')),
            ],
            options={
                'ordering': ['-accessed'],
            },
        ),
    ]
