# Generated by Django 4.0.2 on 2022-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0003_usertextaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertext',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
